### PR TITLE
new phone number input

### PR DESCRIPTION
**Pull request by Alphonce-Mutebi**
Integrated new phone number input to address this: https://github.com/WakalaDAO/wakala-interface/issues/218 and https://github.com/WakalaDAO/wakala-interface/issues/217

### CODE REVIEW

**Review by AbijahKaj — CHANGES_REQUESTED** [review]
IMG_D5FB6B334017-1

Your component doesn't look nor behave like the design.

**Comment by Alphonce-Mutebi** [comment]
@AbijahKaj @Chegemartinx  I used this phone number input based on the suggestinon made by @steffenkrogmann  here: https://github.com/WakalaDAO/wakala-interface/issues/218

**Comment by AbijahKaj** [comment]
> @AbijahKaj @Chegemartinx I used this phone number input based on the suggestinon made by @steffenkrogmann here: #218

The redundant phone input was introduced by Henrique's PR (probably by a refactoring error), nonetheless that section looks and works differently than intended. There're also other country picker packages...

**Comment by steffenkrogmann** [comment]
@Alphonce-Mutebi @AbijahKaj is the screenshot what alphonce built?

I like it much better than the design. Much cleaner. Let's go with it.

I think the original design was kinda copies from Valora and we never questioned it.

**Comment by steffenkrogmann** [comment]
@Chegemartinx please update the figmas as well so that they are consistent with the app because if the video animation

**Comment by AbijahKaj** [comment]
> @Alphonce-Mutebi @AbijahKaj is the screenshot what alphonce built?
> 
> I like it much better than the design. Much cleaner. Let's go with it.
> 
> I think the original design was kinda copies from Valora and we never questioned it.

Great then!

**Review by AbijahKaj — APPROVED** [review]

**Review by sebastiaohns — APPROVED** [review]

**Pull request merged**
